### PR TITLE
feat: The HTTP module supports set Cookie

### PR DESCRIPTION
**Pull request by kkumar-gcc**
Closes # 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by devhaozi** [comment]
@kkumar-gcc tests failed

**Comment by kkumar-gcc** [comment]
> @kkumar-gcc tests failed

I think this will be fixed after merging this PR: https://github.com/goravel/framework/pull/369

**Review by hwbrzzl — CHANGES_REQUESTED** [review]
The logic is good, please optimize the unit test. 👍

**Review by hwbrzzl — APPROVED** [review]
Great job 👍

**Pull request merged**
